// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dRSAmRpUZLudG29s4CqvRvFmVcTOmVE',
    appId: '1:647154132280:web:7be303c4b584531d618dcd',
    messagingSenderId: '647154132280',
    projectId: 'pazcastanhal-809cd',
    authDomain: 'pazcastanhal-809cd.firebaseapp.com',
    storageBucket: 'pazcastanhal-809cd.firebasestorage.app',
    measurementId: 'G-P3XHC5X1FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-a9PqW60Tu1VTzLVdGLATIU-ygatRMFc',
    appId: '1:647154132280:android:0dc96103ed39097b618dcd',
    messagingSenderId: '647154132280',
    projectId: 'pazcastanhal-809cd',
    storageBucket: 'pazcastanhal-809cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC21txMxco0GRSfPGxiPSgw0fzJUNNWKws',
    appId: '1:647154132280:ios:af8c041c6690c57f618dcd',
    messagingSenderId: '647154132280',
    projectId: 'pazcastanhal-809cd',
    storageBucket: 'pazcastanhal-809cd.firebasestorage.app',
    androidClientId: '647154132280-hare8uupge5ocbdvedmmqg11lp6sfst7.apps.googleusercontent.com',
    iosClientId: '647154132280-8ipqnp4ifd2a8ds09br5hv66gm2jhupt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pazCastanhal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC21txMxco0GRSfPGxiPSgw0fzJUNNWKws',
    appId: '1:647154132280:ios:af8c041c6690c57f618dcd',
    messagingSenderId: '647154132280',
    projectId: 'pazcastanhal-809cd',
    storageBucket: 'pazcastanhal-809cd.firebasestorage.app',
    androidClientId: '647154132280-hare8uupge5ocbdvedmmqg11lp6sfst7.apps.googleusercontent.com',
    iosClientId: '647154132280-8ipqnp4ifd2a8ds09br5hv66gm2jhupt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pazCastanhal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4dRSAmRpUZLudG29s4CqvRvFmVcTOmVE',
    appId: '1:647154132280:web:1bc85f426dd8c2ec618dcd',
    messagingSenderId: '647154132280',
    projectId: 'pazcastanhal-809cd',
    authDomain: 'pazcastanhal-809cd.firebaseapp.com',
    storageBucket: 'pazcastanhal-809cd.firebasestorage.app',
    measurementId: 'G-P9XE5ZBHVC',
  );
}
